In [4]:
#replaced the matrix and linear equation analysis.py file
import numpy as np

In [5]:
def LU(A):

    '''Do the guassian elemenation'''
    '''in fact, this is also called doolittle's algorithm'''
    
    U=A.copy()
    tol=1e-6
    dim=U.shape[0]
    det=1
    L=np.eye(dim,dtype=float)
    P=L.copy()
    for i in range(1,dim):
        det*=U[i-1,i-1]
        for j in range(i,dim):
            L[j,i-1]=(U[j,i-1]/U[i-1,i-1])
            U[j,:]-=(U[j,i-1]/U[i-1,i-1])*U[i-1,:]
    return U,L,det

In [6]:
#input depend on question and user
A=np.zeros((5,5))
for i in range(5):
    for j in range(5):
        if j>i:
            A[i,j]=0
        else:
            A[i,j]=2*(i+1)/(i+j+2)

dim=A.shape[0]
f=np.ones((dim,1),dtype=float) #constant term

In [7]:
U,L,det=LU(np.block([A]))
print('determinant= ',det)
print(' ')
print('the upper triangle,as well as the REF=',U) # same as the REF of A
print(' ')
print('the lower triangle=',L)

determinant=  1.0
 
the upper triangle,as well as the REF= [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
 
the lower triangle= [[1.         0.         0.         0.         0.        ]
 [1.33333333 1.         0.         0.         0.        ]
 [1.5        1.2        1.         0.         0.        ]
 [1.6        1.33333333 1.14285714 1.         0.        ]
 [1.66666667 1.42857143 1.25       1.11111111 1.        ]]


In [8]:
# the cholesky decomposition, note that cholesky is only valid for symmetric positive def mat.
# it is very common to see L.T!=U if the matrix does not satisfy the cond.
def cholesky(A):
    U,L,det=LU(A)
    dim=U.shape[0]
    D=np.diag(np.sqrt(np.diag(U)))
    for i in range(dim):
        U[i,:]/=np.diag(U)[i]
    L=L@D
    U=D@U
    return L,D,U

In [9]:
L,D,U=cholesky(A)
print(L)

[[1.         0.         0.         0.         0.        ]
 [1.33333333 1.         0.         0.         0.        ]
 [1.5        1.2        1.         0.         0.        ]
 [1.6        1.33333333 1.14285714 1.         0.        ]
 [1.66666667 1.42857143 1.25       1.11111111 1.        ]]


In [10]:
# crout's factoisation, idk if it is the correct one as crout proposed
def crout(A):
    U,L,det=LU(A)
    dim=U.shape[0]
    D=np.diag(np.diag(U))
    for i in range(dim):
        U[i,:]/=np.diag(U)[i]
    L=L@D
    return L,U

In [11]:
L,U=crout(A)
print(L)
print(' ')
print(U)
print(' ')
print(L@U)

[[1.         0.         0.         0.         0.        ]
 [1.33333333 1.         0.         0.         0.        ]
 [1.5        1.2        1.         0.         0.        ]
 [1.6        1.33333333 1.14285714 1.         0.        ]
 [1.66666667 1.42857143 1.25       1.11111111 1.        ]]
 
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
 
[[1.         0.         0.         0.         0.        ]
 [1.33333333 1.         0.         0.         0.        ]
 [1.5        1.2        1.         0.         0.        ]
 [1.6        1.33333333 1.14285714 1.         0.        ]
 [1.66666667 1.42857143 1.25       1.11111111 1.        ]]


In [12]:
def RREF(A):
    U=LU(A)[0]
    dim=U.shape[0]
    
    for i in range(dim-1,0,-1):
        for j in range(i):
            U[j,:]-=(U[j,i]/U[i,i])*U[i,:]
            U[j,:]/=U[j,j]
            #print(U)
    U[dim-1,:]/=U[dim-1,dim-1]
    return U

In [13]:
R=RREF(np.block([U,np.eye(dim)]))
print(R)

[[1. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]]


In [14]:
Ainv=RREF(np.block([A,np.eye(dim)]))[:,dim:]
Ainv

array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [-1.33333333,  1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.1       , -1.2       ,  1.        ,  0.        ,  0.        ],
       [ 0.06349206,  0.03809524, -1.14285714,  1.        ,  0.        ],
       [ 0.0425485 ,  0.02910053,  0.01984127, -1.11111111,  1.        ]])

In [15]:
Ainv.dot(f)

array([[ 1.        ],
       [-0.33333333],
       [-0.1       ],
       [-0.04126984],
       [-0.01962081]])

In [16]:
# some special matrices, 
# the inputs are the information that we only need when constructing the matrices

def tridiag(dim,l,m,u):
    '''dimension, lower diag, middle diag, upper diag'''
    T=np.zeros((dim,dim))
    T[0,0],T[0,1]=m,u
    T[-1,-1],T[-1,-2]=m,l
    for i in range(1,dim-1):
        T[i,i-1]=l
        T[i,i]=m
        T[i,(i+1)%dim]=u
    return T

def DFT(dim):
    '''the dst matrix is just the negative of 1st quater of this matrix,
    and the inverse of it is the 1st quater of this matrix'''
    
    w=np.exp(-2j*np.pi/dim)
    D=np.ones((dim,dim),dtype=complex)
    for i in range(dim):
        for j in range(dim):
            D[i,j]=w**(i*j)
    return D

def iDFT(dim):
    w=np.exp(2j*np.pi/dim)
    D=np.ones((dim,dim),dtype=complex)
    for i in range(dim):
        for j in range(dim):
            D[i,j]=w**(i*j)
    D/=dim
    return D

def circulant(vector): 
    vec=vector.copy()
    dim=len(vec)
    V=np.zeros((dim,dim))
    inter=tridiag(dim,0,0,1)
    inter[-1,0]=1
    V[0,:]=vec
    for i in range(1,dim):
        vec=vec.dot(inter)
        V[i,:]=vec
    return V

In [17]:
vec=np.array([1,0,0,0,0],dtype=float)
dim=vec.shape[0]
A=circulant(vec)
D=DFT(dim)
iD=iDFT(dim)
print(D)

[[ 1.        +0.j          1.        +0.j          1.        +0.j
   1.        +0.j          1.        +0.j        ]
 [ 1.        +0.j          0.30901699-0.95105652j -0.80901699-0.58778525j
  -0.80901699+0.58778525j  0.30901699+0.95105652j]
 [ 1.        +0.j         -0.80901699-0.58778525j  0.30901699+0.95105652j
   0.30901699-0.95105652j -0.80901699+0.58778525j]
 [ 1.        +0.j         -0.80901699+0.58778525j  0.30901699-0.95105652j
   0.30901699+0.95105652j -0.80901699-0.58778525j]
 [ 1.        +0.j          0.30901699+0.95105652j -0.80901699+0.58778525j
  -0.80901699-0.58778525j  0.30901699-0.95105652j]]


In [18]:
A=np.array([[4,1,1,0],[1,4,1,1],[1,1,4,1],[0,1,1,4]],dtype=float)
U1=np.array([[1,0,0,0],[0,1,0,-0.25],[0,0,1,-0.25],[0,0,0,1]],dtype=float)
A1=U1.dot(A)
U2=np.array([[1,0,-1/3.75,0],[0,1,-0.75/3.75,0],[0,0,1,0],[0,0,0,1]],dtype=float)
A2=U2.dot(A1)
U3=np.array([[1,-0.8/3.6,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]],dtype=float)
A3=U3.dot(A2)
print(A3)

[[ 3.55555556e+00 -3.08395285e-17  2.31296463e-17  0.00000000e+00]
 [ 8.00000000e-01  3.60000000e+00 -4.16333634e-17  0.00000000e+00]
 [ 1.00000000e+00  7.50000000e-01  3.75000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  1.00000000e+00  4.00000000e+00]]


In [19]:
U=U3.dot(U2).dot(U1)

In [20]:
U.dot(A3)

array([[ 3.15555556, -0.85555556, -0.72222222,  0.44444444],
       [ 0.6       ,  3.25      , -0.95      , -0.8       ],
       [ 1.        ,  0.5       ,  3.5       , -1.        ],
       [ 0.        ,  1.        ,  1.        ,  4.        ]])

In [21]:
# the SVD factorisation, which is the general eigenvalue decomposition
# suppose diagonalising a matrix is doable.

A=np.array([[1,2],[3,4]],dtype=float)
X=A.T.dot(A)
